"""derive_schematic_pins.py — 從 SSOT pin_layout 衍生 2D schematic 的「真實 I/O 孔位」。

擬真接線重作 Stage 1:取代 v6/schematic/comp-specs.js 手猜的 COMP_PINS（normalized
[side, fraction]）為真實 datasheet 座標。輸出 v6/data/schematic-pins.js（window.SCHEM_PINS）
供 elk-layout.js 同步讀取。

每 pin = { name, num, nx, ny, side, type, vd, group }，其中
  nx = x_mm / length_mm, ny = y_mm / width_mm（元件 footprint 內的真實歸一化座標）
  side = SSOT header_group.side → 螢幕邊（bottom→SOUTH/top→NORTH/left→WEST/right→EAST）。

用法：python -m scripts.derive_schematic_pins         # 寫檔
      python -m scripts.derive_schematic_pins --check  # 只報、不寫（drift gate 用）
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SSOT = _ROOT / "data" / "component_datasheet_verified.json"
_OUT = _ROOT / "v6" / "data" / "schematic-pins.js"

# schematic compKey ↔ SSOT class（鏡像 lib/wiring/power_inject.py SHORT_TO_CLASS，
# 僅取 2D schematic 會畫的元件）。MCU 由 mcu-ports.js 管,此處只出周邊元件。
COMPKEY_TO_CLASS: dict[str, str] = {
    "NeoPixel": "Lighting-NeoPixel-class",
    "LED_Single": "Lighting-LED-PWM-class",
    "LED_RGB": "Lighting-LED-RGB-class",
    "Speaker": "MP3-Module-class",
    "Buzzer": "Buzzer-Active-class",
    "OLED": "Display-OLED-class",
    "LCD": "Display-LCD-class",
    "Servo": "Motor-Servo-class",
    "DCMotor": "Motor-DC-class",
    "Relay": "Relay-Module-class",
    "Pump": "Pump-Water-class",
    "TempHumid": "Sensor-TempHumid-class",
    "Ultrasonic": "Sensor-Ultrasonic-class",
    "PIR": "Sensor-PIR-class",
    "SoilMoisture": "Sensor-SoilMoisture-class",
    "Light": "Sensor-Light-class",
    "MSGEQ7": "Sensor-MSGEQ7-class",
    "Button": "Button-class",
    "Switch": "Switch-class",
    "Stepper": "Motor-Stepper-class",
    "BatteryAA": "Battery-AA-class",
    "BatteryLiPo": "Battery-LiPo-class",
    "USB5V": "USB-5V-class",
}

# SSOT header_group.side → 螢幕邊。座標慣例待 Chrome F5 校(bottom/top 可能需互換)。
# top_end:長條探針(SoilMoisture)的近端短邊。框長軸水平(REGISTRY_MM 98×23,w=L),
#   header 在 x_mm=93(高 x 末端)、銅探針 blade 在低 x(on_board copper_trace cx≈10–30)
#   → 近端接頭側 = 右短邊 = EAST。與既有 realPinToPort 對 side=null 的最近邊推斷同結果,
#   差別在改由 SSOT 顯式宣告(Stage1「pin 用真 SSOT 值,不靠 render 端推斷」)。
# 註:face / 其他 *_end 不在 header_groups(face 僅見於 on_board_components,非本 deriver 路徑),故不映。
_SIDE_MAP = {"bottom": "SOUTH", "top": "NORTH", "left": "WEST", "right": "EAST", "rear": "SOUTH",
             "top_end": "EAST"}

# DEC-T8(更正:選 B + 移除 fallback):不設 WIP 白名單容忍。任一 COMPKEY 無法衍生 SCHEM_PINS
# = 缺口,--check 直接 FAIL(靠報錯定位),不靜默容忍。


def derive_pins(ds: dict) -> list[dict]:
    """從一個 class 的 datasheet 衍生 schematic pin 清單(真實座標)。"""
    if not ds or not ds.get("physical") or not ds.get("pin_layout"):
        return []
    phys = ds["physical"]
    # pin 座標的歸一化 frame = pin 實際所在 footprint。一般元件 = length_mm/width_mm;
    # multi-body 元件(馬達+驅動板,如 Stepper)pin 在「驅動板」→ 用 driver_*_mm(真實 datasheet
    # 欄位,非頂替)。兩者皆無 → raise(no-silent-fallback;靠報錯揪出 SSOT/deriver 缺口)。
    L = phys.get("length_mm") or phys.get("driver_length_mm")
    W = phys.get("width_mm") or phys.get("driver_width_mm")
    if not L or not W:
        raise ValueError(
            "缺 footprint 尺寸(length_mm / driver_length_mm 皆無)— 無法歸一化 pin 座標(拒絕頂替)")
    out: list[dict] = []
    for hg in (ds["pin_layout"].get("header_groups") or []):
        side = _SIDE_MAP.get(hg.get("side"))  # face/未知 → None,前端依 type 補
        for p in (hg.get("pins") or []):
            out.append({
                "name": p.get("name"),
                "num": p.get("num"),
                "nx": round((p.get("x_mm") or 0) / L, 4),
                "ny": round((p.get("y_mm") or 0) / W, 4),
                "side": side,
                "type": p.get("type"),
                "vd": p.get("voltage_domain"),
                "group": hg.get("name"),
            })
    return out


def build() -> dict:
    ssot = json.loads(_SSOT.read_text(encoding="utf-8"))
    pins: dict[str, list[dict]] = {}
    missing: list[str] = []
    for compkey, cls in COMPKEY_TO_CLASS.items():
        ds = ssot.get(cls)
        if ds is None:
            missing.append(f"{compkey}({cls}: 無此 class)")
            continue
        try:
            derived = derive_pins(ds)
        except ValueError as exc:
            missing.append(f"{compkey}({cls}: {exc})")
            continue
        if not derived:
            missing.append(f"{compkey}({cls}: 無 pin_layout)")
            continue
        pins[compkey] = derived
    return {"pins": pins, "missing": missing}


def _render_js(pins: dict) -> str:
    body = json.dumps(pins, ensure_ascii=False, indent=2)
    cls_map = json.dumps(COMPKEY_TO_CLASS, ensure_ascii=False, indent=2)
    return (
        "// schematic-pins.js — AUTO-GENERATED by scripts/derive_schematic_pins.py\n"
        "// 真實 I/O 孔位(SSOT data/component_datasheet_verified.json pin_layout 衍生)\n"
        "// + compKey→class 橋接(供 2D 資料驅動真投影查 COMPONENT_DIMENSIONS[<class>].ports)。\n"
        "// 勿手改;重生:python -m scripts.derive_schematic_pins\n"
        "// 每 pin: {name,num,nx,ny,side,type,vd,group};nx=x_mm/L, ny=y_mm/W(footprint 歸一化)。\n"
        "(() => {\n"
        f"  window.SCHEM_PINS = {body};\n"
        f"  window.COMPKEY_TO_CLASS = {cls_map};\n"
        "})();\n"
    )


def _drift_summary(expected: str, actual: str) -> str:
    import difflib
    diff = [ln for ln in difflib.unified_diff(
        actual.splitlines(), expected.splitlines(), lineterm="", n=0)
        if ln and ln[0] in "+-" and not ln.startswith(("+++", "---"))]
    head = "; ".join(diff[:6])
    return (f"{_OUT.name} 與 SSOT 衍生結果不符（{len(diff)} 行差異）: {head}"
            " … → 請跑 `python -m scripts.derive_schematic_pins` 重生")


def _check_problems(res: dict) -> tuple[int, list[str]]:
    """真 drift gate：① 元件意外掉出（非 WIP 白名單）② 輸出與 SSOT 衍生不符。
    回傳 (exit_code, problems)。problems 空 = PASS。可單測（meta-gate 防假綠回歸）。"""
    problems: list[str] = []
    for m in res["missing"]:
        problems.append(f"元件無法衍生 SCHEM_PINS（缺 SSOT 資料/deriver 不支援；no-silent-fallback）: {m}")
    if not _OUT.exists():
        problems.append(f"{_OUT.name} 不存在 → 請先 `python -m scripts.derive_schematic_pins`")
    else:
        expected = _render_js(res["pins"])
        actual = _OUT.read_text(encoding="utf-8")
        if expected != actual:
            problems.append(_drift_summary(expected, actual))
    return (1 if problems else 0, problems)


def main() -> int:
    check = "--check" in sys.argv
    res = build()
    print(f"[schematic-pins] derived {len(res['pins'])} components from SSOT pin_layout")
    for m in res["missing"]:
        print(f"  [FAIL] {m}")
    if check:
        code, problems = _check_problems(res)
        if code:
            print("[schematic-pins][check] FAIL:")
            for p in problems:
                print("  - " + p)
        else:
            print("[schematic-pins][check] PASS — 無 drift、無意外掉出")
        return code
    _OUT.write_text(_render_js(res["pins"]), encoding="utf-8")
    print(f"[schematic-pins] wrote {_OUT.relative_to(_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
